version: "3.8"

services:
  nats-streaming:
    image: nats-streaming:0.9.2
    ports:
      - "4222:4222"
    restart: always

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: always

  # meow:
  #   build: "."
  #   command: "meow-service"
  #   depends_on:
  #     - "postgres"
  #     - "nats"
  #   ports:
  #     - "8080"
  #   environment:
  #     POSTGRES_DB: "meower"
  #     POSTGRES_USER: "meower"
  #     POSTGRES_PASSWORD: "123456"
  #     NATS_ADDRESS: "nats:4222"
  # query:
  #   build: "."
  #   command: "query-service"
  #   depends_on:
  #     - "postgres"
  #     - "nats"
  #   ports:
  #     - "8080"
  #   environment:
  #     POSTGRES_DB: "meower"
  #     POSTGRES_USER: "meower"
  #     POSTGRES_PASSWORD: "123456"
  #     NATS_ADDRESS: "nats:4222"
  #     ELASTICSEARCH_ADDRESS: "elasticsearch:9200"
  # pusher:
  #   build: "."
  #   command: "pusher-service"
  #   depends_on:
  #     - "nats"
  #   ports:
  #     - "8080"
  #   environment:
  #     NATS_ADDRESS: "nats:4222"

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
